"""add dedup_key to alerts

Revision ID: 6ed1f38c6114
Revises: b0f26661338e
Create Date: 2026-09-28 11:46:10.237837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed1f38c6114'
down_revision: Union[str, None] = 'b0f26661338e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('dedup_key', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_column('alerts', 'dedup_key')
    # ### end Alembic commands ###
