"""add fact_orders_daily table

Revision ID: b0f26661338e
Revises: ed7e55dd86c9
Create Date: 2026-09-25 12:45:29.218086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f26661338e'
down_revision: Union[str, None] = 'ed7e55dd86c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_orders_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fact_orders_daily_date_region_channel_status', 'fact_orders_daily', ['order_date', 'region', 'channel', 'status'], unique=False)
    op.create_index(op.f('ix_fact_orders_daily_order_date'), 'fact_orders_daily', ['order_date'], unique=False)
    op.create_index(op.f('ix_fact_orders_daily_region'), 'fact_orders_daily', ['region'], unique=False)
    op.create_index(op.f('ix_fact_orders_daily_status'), 'fact_orders_daily', ['status'], unique=False)
    op.create_index(op.f('ix_fact_orders_daily_year'), 'fact_orders_daily', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_orders_daily_year'), table_name='fact_orders_daily')
    op.drop_index(op.f('ix_fact_orders_daily_status'), table_name='fact_orders_daily')
    op.drop_index(op.f('ix_fact_orders_daily_region'), table_name='fact_orders_daily')
    op.drop_index(op.f('ix_fact_orders_daily_order_date'), table_name='fact_orders_daily')
    op.drop_index('ix_fact_orders_daily_date_region_channel_status', table_name='fact_orders_daily')
    op.drop_table('fact_orders_daily')
    # ### end Alembic commands ###
